<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260723194859 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Session management: user_session registry';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE user_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, session_id_hash VARCHAR(64) NOT NULL, user_id INT NOT NULL, user_agent VARCHAR(255) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_session_user ON user_session (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_session_hash ON user_session (session_id_hash)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE user_session');
    }
}
