<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260722210829 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Занятия: таблица lesson (преподаватель, ученик, инструмент, время, статус) с индексом teacher+starts_at';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE lesson (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, duration_minutes INT NOT NULL, status VARCHAR(255) NOT NULL, comment TEXT DEFAULT NULL, cancel_reason TEXT DEFAULT NULL, teacher_id INT NOT NULL, client_id INT NOT NULL, instrument_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F87474F341807E1D ON lesson (teacher_id)');
        $this->addSql('CREATE INDEX IDX_F87474F319EB6921 ON lesson (client_id)');
        $this->addSql('CREATE INDEX IDX_F87474F3CF11D9C ON lesson (instrument_id)');
        $this->addSql('CREATE INDEX idx_lesson_teacher_starts ON lesson (teacher_id, starts_at)');
        $this->addSql('ALTER TABLE lesson ADD CONSTRAINT FK_F87474F341807E1D FOREIGN KEY (teacher_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lesson ADD CONSTRAINT FK_F87474F319EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lesson ADD CONSTRAINT FK_F87474F3CF11D9C FOREIGN KEY (instrument_id) REFERENCES instrument (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE lesson DROP CONSTRAINT FK_F87474F341807E1D');
        $this->addSql('ALTER TABLE lesson DROP CONSTRAINT FK_F87474F319EB6921');
        $this->addSql('ALTER TABLE lesson DROP CONSTRAINT FK_F87474F3CF11D9C');
        $this->addSql('DROP TABLE lesson');
    }
}
