<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260722172407 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Теги клиентов: таблицы tag (уникальное имя) и client_tag (обе связи ON DELETE CASCADE)';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE client_tag (client_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (client_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_242D242719EB6921 ON client_tag (client_id)');
        $this->addSql('CREATE INDEX IDX_242D2427BAD26311 ON client_tag (tag_id)');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(40) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_tag_name ON tag (name)');
        $this->addSql('ALTER TABLE client_tag ADD CONSTRAINT FK_242D242719EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE client_tag ADD CONSTRAINT FK_242D2427BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE client_tag DROP CONSTRAINT FK_242D242719EB6921');
        $this->addSql('ALTER TABLE client_tag DROP CONSTRAINT FK_242D2427BAD26311');
        $this->addSql('DROP TABLE client_tag');
        $this->addSql('DROP TABLE tag');
    }
}
