<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260722224515 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE repertoire_piece (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(160) NOT NULL, composer VARCHAR(120) DEFAULT NULL, status VARCHAR(255) NOT NULL, note TEXT DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, client_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_221A19E419EB6921 ON repertoire_piece (client_id)');
        $this->addSql('CREATE INDEX idx_piece_client_status ON repertoire_piece (client_id, status)');
        $this->addSql('ALTER TABLE repertoire_piece ADD CONSTRAINT FK_221A19E419EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE repertoire_piece DROP CONSTRAINT FK_221A19E419EB6921');
        $this->addSql('DROP TABLE repertoire_piece');
    }
}
