<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260723183832 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Audit log: append-only audit_event table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE audit_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, action VARCHAR(64) NOT NULL, actor_id INT DEFAULT NULL, actor_email VARCHAR(180) DEFAULT NULL, subject_type VARCHAR(64) DEFAULT NULL, subject_id VARCHAR(64) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, user_agent VARCHAR(255) DEFAULT NULL, payload JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_audit_occurred ON audit_event (occurred_at)');
        $this->addSql('CREATE INDEX idx_audit_action ON audit_event (action)');
        $this->addSql('CREATE INDEX idx_audit_actor ON audit_event (actor_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE audit_event');
    }
}
