<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260722230949 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(160) NOT NULL, kind VARCHAR(255) NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, venue VARCHAR(160) DEFAULT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_event_date ON event (date)');
        $this->addSql('CREATE TABLE event_program_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, custom_title VARCHAR(160) DEFAULT NULL, sort_order INT NOT NULL, event_id INT NOT NULL, client_id INT NOT NULL, piece_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FFEE7AEA71F7E88B ON event_program_item (event_id)');
        $this->addSql('CREATE INDEX IDX_FFEE7AEA19EB6921 ON event_program_item (client_id)');
        $this->addSql('CREATE INDEX IDX_FFEE7AEAC40FCFA8 ON event_program_item (piece_id)');
        $this->addSql('ALTER TABLE event_program_item ADD CONSTRAINT FK_FFEE7AEA71F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_program_item ADD CONSTRAINT FK_FFEE7AEA19EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_program_item ADD CONSTRAINT FK_FFEE7AEAC40FCFA8 FOREIGN KEY (piece_id) REFERENCES repertoire_piece (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE event_program_item DROP CONSTRAINT FK_FFEE7AEA71F7E88B');
        $this->addSql('ALTER TABLE event_program_item DROP CONSTRAINT FK_FFEE7AEA19EB6921');
        $this->addSql('ALTER TABLE event_program_item DROP CONSTRAINT FK_FFEE7AEAC40FCFA8');
        $this->addSql('DROP TABLE event');
        $this->addSql('DROP TABLE event_program_item');
    }
}
