<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260722195445 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Справочник инструментов: таблицы instrument и client_instrument + базовый набор из 12 инструментов';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE client_instrument (client_id INT NOT NULL, instrument_id INT NOT NULL, PRIMARY KEY (client_id, instrument_id))');
        $this->addSql('CREATE INDEX IDX_ACEB549C19EB6921 ON client_instrument (client_id)');
        $this->addSql('CREATE INDEX IDX_ACEB549CCF11D9C ON client_instrument (instrument_id)');
        $this->addSql('CREATE TABLE instrument (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(80) NOT NULL, category VARCHAR(255) NOT NULL, sort_order INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_instrument_name ON instrument (name)');
        $this->addSql('ALTER TABLE client_instrument ADD CONSTRAINT FK_ACEB549C19EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE client_instrument ADD CONSTRAINT FK_ACEB549CCF11D9C FOREIGN KEY (instrument_id) REFERENCES instrument (id) ON DELETE CASCADE');

        // Базовый набор — чтобы справочник не был пустым сразу после развёртывания
        $seed = [
            ['Фортепиано', 'keyboard', 10],
            ['Синтезатор', 'keyboard', 20],
            ['Аккордеон', 'keyboard', 30],
            ['Скрипка', 'strings', 40],
            ['Виолончель', 'strings', 50],
            ['Гитара', 'strings', 60],
            ['Домра', 'strings', 70],
            ['Флейта', 'winds', 80],
            ['Саксофон', 'winds', 90],
            ['Ударные', 'percussion', 100],
            ['Вокал', 'vocal', 110],
            ['Сольфеджио', 'keyboard', 120],
        ];

        foreach ($seed as [$name, $category, $sortOrder]) {
            $this->addSql(
                'INSERT INTO instrument (name, category, sort_order) VALUES (:name, :category, :sort_order)',
                ['name' => $name, 'category' => $category, 'sort_order' => $sortOrder],
            );
        }
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE client_instrument DROP CONSTRAINT FK_ACEB549C19EB6921');
        $this->addSql('ALTER TABLE client_instrument DROP CONSTRAINT FK_ACEB549CCF11D9C');
        $this->addSql('DROP TABLE client_instrument');
        $this->addSql('DROP TABLE instrument');
    }
}
