apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pet-symphony-allow
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: pet-symphony
  policyTypes:
    - Egress
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: pet-symphony-db
      ports:
        - port: 5432
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: pet-symphony-cache
      ports:
        - port: 6379
