apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pet-symphony-stage

resources:
  - ../../base

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: pet-symphony
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: pet-symphony-config
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: pet-symphony

images:
  - name: pet-symphony
    newName: ghcr.io/enrinko/pet-symphony
    newTag: ""
