apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pet-symphony

commonLabels:
  app.kubernetes.io/name: pet-symphony
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy-deny-all.yaml
  - networkpolicy-allow.yaml
  - poddisruptionbudget.yaml
  - ingress.yaml

images:
  - name: pet-symphony
    newName: ghcr.io/enrinko/pet-symphony
    newTag: "latest"
