apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pet-symphony
spec:
  rules:
    - host: pet-symphony.dev.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pet-symphony
                port:
                  name: http
  tls:
    - hosts:
        - pet-symphony.dev.local
      secretName: pet-symphony-dev-tls
